publisher/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'', include('apps.api.urls', 'api')),
    url(r'', include('apps.web.urls', 'web')),
]

apps/web/models.py
from django.db import models


# Create your models here.


class Rsa(models.Model):
    # 私钥
    status_choices = (
        (1, '启用'),
        (2, '停用'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices)
    username = models.CharField(verbose_name='用户', max_length=32, default='root')
    private_key = models.TextField(verbose_name='私钥')

    def __str__(self):
        return self.status


class Server(models.Model):
    # 　 主机表， 所有主机的ip
    hostname = models.CharField(verbose_name='主机名', max_length=32)

    def __str__(self):
        return self.hostname


class Project(models.Model):
    # 项目表
    # repo地址 支持http, https, ftp, ftps
    title = models.CharField(verbose_name='项目名', max_length=32)
    repo = models.URLField(verbose_name='git仓库地址')

    def __str__(self):
        return self.title


class ProjectEnv(models.Model):
    # 项目环境
    project = models.ForeignKey(verbose_name='项目', to='Project')
    env_choices = (
        (1, '测试'),
        (2, '正式')
    )
    env = models.IntegerField(verbose_name='环境', choices=env_choices)
    path = models.CharField(verbose_name='线上部署路径', max_length=128)
    servers = models.ManyToManyField(verbose_name='服务器', to='Server')

    def __str__(self):
        return "%s(%s)" % (self.project.title, self.get_env_display())


class DeployTask(models.Model):
    # 部署任务表
    uid = models.CharField(verbose_name='任务ID', max_length=64,
                           help_text="任务ID格式为：项目-版本-时间，例如 cmdb-v1-201911012359.zip")
    status_choices = (
        (1, '待发布'),
        (2, '发布中'),
        (3, '成功'),
        (4, '失败'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=1)
    env = models.ForeignKey(verbose_name='环境', to='ProjectEnv')
    # 正式发布用tag
    tag = models.CharField(verbose_name='版本', max_length=32, null=True, blank=True)
    # 测试发布用branch 、commit
    branch = models.CharField(verbose_name='分支', max_length=32, null=True, blank=True)
    commit = models.CharField(verbose_name='提交记录', max_length=40, null=True, blank=True)

    deploy_type_choice = (
        (1, '全量服务器上线'),
        (2, '自定义服务器上线'),
    )
    deploy_type = models.PositiveSmallIntegerField(verbose_name='上线类型', choices=deploy_type_choice)
    # deploy_server = models.ForeignKey(verbose_name='自定义服务器', to="Server", blank=True)
    # deploy_record = models.ManyToManyField(verbose_name='部署记录',
    #                                        to='Server',
    #                                        through='DeployServer',
    #                                        through_fields=('deploy', 'server'))

    def __str__(self):
        return self.get_status_display()


class DeployServer(models.Model):
    """
    上线服务器
    """
    deploy = models.ForeignKey(verbose_name='部署', to='DeployTask')
    server = models.ForeignKey(verbose_name='服务器', to='Server')
    status_choices = (
        (1, '待发布'),
        (2, '发布中'),
        (3, '失败'),
        (4, '成功'),
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices,default=1)

    def __str__(self):
        return self.server.hostname


class Diagram(models.Model):
    """发布图标"""
    task = models.ForeignKey(verbose_name='发布任务', to='DeployTask')
    text = models.CharField(verbose_name='文本', max_length=32)
    status_choices = (
        ('gray', '待执行'),
        ('green', '成功'),
        ('red', '失败'),
    )
    status = models.CharField(verbose_name='状态', max_length=32, choices=status_choices, default='gray')
    parent = models.ForeignKey(verbose_name='父节点', to='self', null=True, blank=True)
    deploy_record = models.ForeignKey(verbose_name='服务器发布记录', to='DeployServer', null=True, blank=True)
    log = models.TextField(verbose_name='日志', null=True, blank=True)

apps/web/views.py
import os
import copy
import shutil

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from django.conf import settings

from utils.repository import GitRepository
from utils.ssh import SSHProxy
from apps.web import models
from apps.web import forms
from utils import custom_paginator
from utils.response import BaseResponse


# Create your views here.


def home(request):
    servers = models.Server.objects.all()
    context = {
        'servers': servers,
    }
    return render(request, 'web/server.html', context)


def rsa(request):
    # 获取所有私钥列表
    try:
        rsas = models.Rsa.objects.all()
        request_data = copy.copy(request.GET)
        cur_page_num = request.GET.get('page')
        total_count = rsas.count()
        obj_per_page = settings.PER_PAGE_COUNT
        page_tab_num = settings.PAGE_NUMBER_SHOW
        page_obj = custom_paginator.CustomPage(cur_page_num, total_count, obj_per_page, page_tab_num,
                                               request_data)
        rsa_list = rsas[page_obj.start_page_num:page_obj.end_page_num]
        page_html = page_obj.gen_page_html()
        context = {
            'rsas': rsa_list,
            'page_html': page_html,
        }
    except ConnectionError:
        return render(request, '404.html')

    return render(request, 'web/rsa.html', context)


def rsa_delete(request, pk):
    models.Rsa.objects.filter(pk=pk).delete()
    return redirect('web:rsa')


def rsa_add(request):
    # 添加rsa
    if request.method == 'GET':
        # 添加rsa
        rsa_form = forms.RsaForm()
        context = {'rsa_form': rsa_form}
        return render(request, 'web/rsa_add_edit.html', context)
    else:
        rsa_form = forms.RsaForm(data=request.POST)
        if rsa_form.is_valid():
            rsa_form.save()
            return redirect('web:rsa')
        context = {'rsa_form': rsa_form}
        return render(request, 'web/rsa_add_edit.html', context)


def rsa_edit(request, pk):
    # 编辑rsa
    if request.method == 'GET':
        rsa_obj = models.Rsa.objects.filter(pk=pk).first()
        rsa_form = forms.RsaForm(instance=rsa_obj)
        context = {'rsa_form': rsa_form}
        return render(request, 'web/rsa_add_edit.html', context)
    else:
        rsa_obj = models.Rsa.objects.filter(pk=pk).first()
        rsa_form = forms.RsaForm(instance=rsa_obj, data=request.POST)
        if rsa_form.is_valid():
            rsa_form.save()
            return redirect('web:rsa')
        context = {'rsa_form': rsa_form}
        return render(request, 'web/rsa_add_edit.html', context)


def server(request):
    # 服务器列表
    try:
        servers = models.Server.objects.all()
        request_data = copy.copy(request.GET)
        cur_page_num = request.GET.get('page')
        total_count = servers.count()
        obj_per_page = settings.PER_PAGE_COUNT
        page_tab_num = settings.PAGE_NUMBER_SHOW
        page_obj = custom_paginator.CustomPage(cur_page_num, total_count, obj_per_page, page_tab_num,
                                               request_data)
        servers = servers[page_obj.start_page_num:page_obj.end_page_num]
        page_html = page_obj.gen_page_html()
        context = {
            'servers': servers,
            'page_html': page_html,
        }
    except ConnectionError:
        return render(request, '404.html')

    return render(request, 'web/server.html', context)


def server_delete(request, pk):
    models.Server.objects.filter(pk=pk).delete()
    return redirect('web:server')


def server_add(request):
    # 添加server
    if request.method == 'GET':

        server_form = forms.ServerForm()
        context = {'form': server_form}
        return render(request, 'web/add_edit_form.html', context)
    else:
        server_form = forms.ServerForm(data=request.POST)
        if server_form.is_valid():
            server_form.save()
            return redirect('web:server')
        context = {'form': server_form}
        return render(request, 'web/add_edit_form.html', context)


def server_edit(request, pk):
    # 编辑server
    server_obj = models.Server.objects.filter(pk=pk).first()
    if request.method == 'GET':
        server_form = forms.ServerForm(instance=server_obj)
        context = {'form': server_form}
        return render(request, 'web/add_edit_form.html', context)
    else:
        server_form = forms.ServerForm(instance=server_obj, data=request.POST)
        if server_form.is_valid():
            server_form.save()
            return redirect('web:server')
        context = {'form': server_form}
        return render(request, 'web/add_edit_form.html', context)


def project(request):
    try:
        projects = models.Project.objects.all()
        request_data = copy.copy(request.GET)
        cur_page_num = request.GET.get('page')
        total_count = projects.count()
        obj_per_page = settings.PER_PAGE_COUNT
        page_tab_num = settings.PAGE_NUMBER_SHOW
        page_obj = custom_paginator.CustomPage(
            cur_page_num, total_count, obj_per_page, page_tab_num, request_data
        )
        project_list = projects[page_obj.start_page_num:page_obj.end_page_num]
        page_html = page_obj.gen_page_html()
        context = {
            'projects': project_list,
            'page_html': page_html
        }
    except ConnectionError:
        return render(request, '404.html')
    return render(request, 'web/project.html', context)


def project_delete(request, pk):
    project_obj = models.Project.objects.filter(pk=pk).first()
    project_obj.delete()
    return redirect('web:project')


def project_add(request):
    if request.method == 'GET':
        project_form = forms.ProjectForm()
        context = {'form': project_form}
        return render(request, 'web/add_edit_form.html', context)
    else:
        project_form = forms.ProjectForm(data=request.POST)
        if project_form.is_valid():
            project_form.save()
            return redirect('web:project')
        context = {'form': project_form}
        return render(request, 'web/add_edit_form.html', context)


def project_edit(request, pk):
    if request.method == 'GET':

        project_obj = models.Project.objects.filter(pk=pk).first()
        project_form = forms.ProjectForm(instance=project_obj)
        context = {'form': project_form}
        return render(request, 'web/add_edit_form.html', context)
    else:
        project_obj = models.Project.objects.filter(pk=pk).first()
        project_form = forms.ProjectForm(instance=project_obj, data=request.POST)
        if project_form.is_valid():
            project_form.save()
            return redirect('web:project')
        context = {"form": project_form}
        return render(request, 'web/add_edit_form.html', context)


def project_env(request):
    try:
        project_envs = models.ProjectEnv.objects.all()
        request_data = copy.copy(request.GET)
        cur_page_num = request.GET.get('page')
        total_count = project_envs.count()
        obj_per_page = settings.PER_PAGE_COUNT
        page_tab_num = settings.PAGE_NUMBER_SHOW
        page_obj = custom_paginator.CustomPage(cur_page_num,
                                               total_count,
                                               obj_per_page,
                                               page_tab_num,
                                               request_data)
        project_env_list = project_envs[page_obj.start_page_num:page_obj.end_page_num]
        page_html = page_obj.gen_page_html()
        context = {'project_envs': project_env_list, 'page_html': page_html}
    except ConnectionError:
        return render(request, '404.html')
    return render(request, 'web/project_env.html', context)


def project_env_delete(request, pk):
    project_env_obj = models.ProjectEnv.objects.filter(pk=pk).first()
    project_env_obj.delete()
    return redirect('web:project_env')


def project_env_add(request):
    if request.method == 'GET':
        project_env_form = forms.ProjectEnvForm()
        context = {'form': project_env_form}
        return render(request, 'web/add_edit_form.html', context)
    else:
        project_env_form = forms.ProjectEnvForm(data=request.POST)
        if project_env_form.is_valid():
            project_env_form.save()
            return redirect('web:project_env')
        context = {'form': project_env_form}
        return render(request, 'web/add_edit_form.html', context)


def project_env_edit(request, pk):
    if request.method == 'GET':
        project_env_obj = models.ProjectEnv.objects.filter(pk=pk).first()
        project_env_form = forms.ProjectEnvForm(instance=project_env_obj)
        context = {'form': project_env_form}
        return render(request, 'web/add_edit_form.html', context)
    else:
        project_env_obj = models.ProjectEnv.objects.filter(pk=pk).first()
        project_env_form = forms.ProjectEnvForm(instance=project_env_obj, data=request.POST)
        if project_env_form.is_valid():
            project_env_form.save()
            return redirect('web:project_env')
        context = {'form': project_env_form}
        return render(request, 'web/add_edit_form.html', context)


def deploy_task(request, env_id):
    project_env_obj = models.ProjectEnv.objects.filter(pk=env_id).first()
    deploy_tasks = models.DeployTask.objects.filter(env=project_env_obj)

    context = {'deploy_tasks': deploy_tasks,
               'project_env_obj': project_env_obj
               }
    return render(request, 'web/deploy_task.html', context)


def deploy_task_add(request, env_id):
    env_object = models.ProjectEnv.objects.filter(id=env_id).first()  # 将env_object传给form表单，获取关联表的值
    if request.method == 'GET':
        deploy_task_form = forms.DeployTaskForm(env_object)
        context = {'deploy_task_form': deploy_task_form, 'env_object': env_object}
        return render(request, 'web/deploy_task_add_edit.html', context)
    else:

templates/web/add_edit_form.html
{% extends 'web/base.html' %}
{% block content %}
    <div class="container">
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">{{field.label}}</label>
                <div class="col-sm-10">
                    {{ field }}
                    <span style="color: red">{{ field.errors.0 }}</span>
                </div>
            </div>
            {% endfor %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="submit" value="保 存" class="btn btn-primary">
                    <span style="color: red">{{ form.non_field_errors.0 }}</span>
                </div>
            </div>
        </form>
    </div>
{% endblock %}



templates/web/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>代码发布系统</title>
    {% endblock title %}
</head>
<link rel="stylesheet" href="{% static 'plugins/bootstrap-3.3.7/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'plugins/font-awesome-4.7.0/css/font-awesome.css' %}">
{% block custom_css %}
{% endblock custom_css %}
<body>
<nav class="navbar navbar-inverse  navbar-fixed-top">
    <div class="container">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'web:server' %}">server</a></li>
                <li><a href="{% url 'web:rsa' %}">RSA</a></li>
                <li><a href="{% url 'web:project' %}">Project</a></li>
                <li><a href="{% url 'web:project_env' %}">Project Env</a></li>
{#                <li><a href="{% url 'web:deploy_task' %}">Deploy Task</a></li>#}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>
<div class="container ">
    <div class="row tip text-center">
        {% block tips %}
            <h3>Code publish</h3>
        {% endblock tips %}
    </div>
        {% block content %}

        {% endblock content %}


</div>
</body>
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-3.3.7/js/bootstrap.js' %}"></script>
{% block custom_js %}
{% endblock custom_js %}
</html>

templates/web/deploy_by_channel.html
{% extends 'web/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deploy Task by channel</title>
</head>
<body>
{% block content %}
    <input id="start" class="btn btn-sm btn-success" value="开始部署"/><p id="connect_status"></p>
    </br>
    <div id="content" class=" col-md-3" style="border:1px dashed cadetblue;min-height: 160px;border-radius: 10px;">
        <!--返回内容将在这里显示  -->
    </div>
    {% for server in deploy_server_list %}
        <div class="col-md-8 col-md-offset-1" style="border: 1px dashed cadetblue ;min-height:160px;border-radius: 10px;">
            <img width="100px" height="100px" src="{% static 'images/server.jpg' %}">
            {{ server }}
            <div class="progress">
                <div id="progress" class="progress-bar" role="progressbar" aria-valuenow="" aria-valuemin="0"
                     aria-valuemax="100"
                     style="">
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="col-md-offset-4">{{ page_html }}</div>
{% endblock content %}
</body>
{% block custom_js %}
    <script>

        var ws = new WebSocket('ws://127.0.0.1:8000/channel/{{ task_id }}/');
        ws.onopen = function (event) {
            $("#connect_status").text('连接成功');
        };
        ws.onmessage = function (event) {
            //# 收到消息时触发
            let content = $("#content");
            let tag = document.createElement('div');
            let data = JSON.parse(event.data);
            status = data['status'];
            let msg = data['msg'];
            let percent = data['percent'];

            tag.innerHTML = '<span style="color:green;">' + status + '</span>' + ':' + msg;
            content.append(tag);
            $("#progress").attr('aria-valuenow', percent);
            let style = 'width:' + percent + '%';
            $("#progress").attr('style', style);

            $("#progress").text(percent + '%');
        };
        ws.onclose = function (event) {
            $("#connect_status").text('断开连接');
            $("#content div").remove();
        }
        $(function () {
            $('#start').click(function () {
                ws.send(JSON.stringify({'action': 'start'}));
            });
        })
    </script>
{% endblock custom_js %}
</html>

templates/web/deploy_task_add_edit.html
{% extends 'web/base.html' %}
{% load static %}
{% block custom_css %}
    <style>
        .loading {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: black;
            opacity: 0.3;
        }

        #loading-icon {
            width: 100px;
            height: 30px;
            position: fixed;
            top: 50%;
            left: 50%;
            margin-left: -50px;
            margin-top: -15px;
        }
    </style>
{% endblock custom_css %}
{% block content %}
    <div id="loading" class="loading hidden">
        <div id="loading-icon">
            <img src="{% static 'images/loading.gif' %}">
        </div>
    </div>
    <!-- 加载动画-->
    <label for="id_project">项目名称:</label>
    <input readonly="readonly" type="text" name="project" maxlength="40" class="form-control" id="id_project"
           value="{{ env_object.project.title }}">
    <label for="id_repo">git地址</label>
    <input readonly="readonly" type="text" name="repo" maxlength="40" class="form-control" id="id_repo"
           value="{{ env_object.project.repo }}">
    <label for="id_env">环境:</label>
    <input readonly="readonly" type="text" name="env" maxlength="40" class="form-control" id="id_env"
           value="{{ env_object.get_env_display }}">
    <label for="id_path">线上路径:</label>
    <input readonly="readonly" type="text" name="path" maxlength="40" class="form-control" id="id_path"
           value="{{ env_object.path }}">
    <label for="id_severs">目标服务器:</label>
{#    <input readonly="readonly" type="text" name="servers" maxlength="40" class="form-control" id="id_servers"#}
{#           value="{% for server in env_object.servers.all %}{{ server }} {% endfor %}">#}
    <form method="post" novalidate>
        {% csrf_token %}
        {{ deploy_task_form }}
        <input type="submit" class="btn btn-success" value="'提交">
    </form>


{% endblock content %}
{% block custom_js %}
    <script>
        $(function () {
            bindChangeEvent();
        });

        // TODO 如果选择了标签，将branch, commit的选项都重置

        function bindChangeEvent() {
            $('#id_branch').change(function () {
                let branch = $(this).val();
                if (branch) {
                    $("#loading").removeClass('hidden');
                    $("#id_commit option:gt(0)").remove(); //每次选择分支时移除commit下大于1的选项，否则更换后不断增多
                    $.ajax({
                        url: '/git/commits/',
                        type: 'get',
                        dataType: 'JSON', //使接收的数据格式为Json,而不用手动转换
                        data: {
                            branch: branch, env_id: "{{ env_object.id}}" // env_id可以从前端 传过来
                        },
                        success: function (res) {
                            if (res.status) {
                                $.each(res.data, function (index, row) {
                                    $("#loading").addClass('hidden');
                                    var $option = $('<option>'); //创建一个jq对象, $option 表示为jq对象
                                    $option.attr('value', row.commit);
                                    let message = row.commit + "--提交者：" + row.author;
                                    $option.text(message);
                                    $("#id_commit").append($option);
                                });

                            } else {
                                // 如果失败了，提示错误信息

                                alert(res.error);
                            }
                        },
                        error: function () {
                            $("#loading").addClass('hidden');

                        }
                    })
                } else {
                    $("#id_commit option:gt(1)").remove(); // 没有选择分支时把所有commit选项去掉
                }
            })
        }
    </script>
{% endblock custom_js %}

templates/web/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.3.7/css/bootstrap.css' %}">
    <title>download git repo</title>
    <style>
        .loading {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: black;
            opacity: 0.3;
        }

        #loading-icon {
            width: 100px;
            height: 30px;
            position: fixed;
            top: 50%;
            left: 50%;
            margin-left: -50px;
            margin-top: -15px;
        }
    </style>
</head>
<body>
<div class="container">
    <div>
        <p>输入远程仓库地址，本地保存目录将与远程目录相</p>
    </div>
    <input name='repo_addr' id='repo_addr' placeholder='请输入repository地址'/>
    <button class="btn btn-success" onclick="download_repo();">下载</button>
</div>
</body>
<div id="loading" class="loading hidden">
    <div id="loading-icon">
        <img src="{% static 'images/loading.gif' %}">
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script>
    function download_repo() {
        let repo_addr = $("#repo_addr").val();
         $("#loading").removeClass('hidden');
        $.ajax({
            url: '/fetch/',
            type: 'POST',
            data: {repo_addr: repo_addr},
            success: function (response) {
                $("#loading").addClass('hidden');
            },
            error: function (resposne) {
                $("#loading").addClass('hidden');
            }
        })
    }
</script>
</html>

templates/web/project.html
{% extends 'web/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project</title>
</head>
<body>
{% block content %}
    <div class="col-md-12">
        <p class="">
            <a href="{% url 'web:project_add' %}">
                <button type="button" class="btn btn-primary">添加项目</button>
            </a>
        </p>
        <p>
        <h3 class="text-center">项目列表</h3>
        </p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">标题</td>
                <td class="success">仓库</td>
                <td class="info">操作</td>
            </tr>
            </thead>
            <tbody>
            <tbody>
            {% for project in projects %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ project.title }}</td>
                    <td>{{ project.repo }}</td>

                    <td>
                        <a style="color: #333333;" href="{% url 'web:project_edit' project.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="{% url 'web:project_delete' project.id %}"><i
                                class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            </tbody>
        </table>

    </div>

{% endblock content %}
</body>
</html>

templates/web/project_add_edit.html
{% extends 'web/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ project_form }}
        <input type="submit" class="btn btn-success" value="提交">
    </form>
{% endblock content %}

templates/web/project_env.html
{% extends 'web/base.html' %}
{% load deploy_num %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project Env</title>
</head>
<body>
{% block content %}
    <div class="col-md-12">
        <p class="">
            <a href="{% url 'web:project_env_add' %}">
                <button type="button" class="btn btn-primary">添加项目环境</button>
            </a>
        </p>
        <p>
        <h3 class="text-center">项目环境列表</h3>
        </p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">所属项目</td>
                <td class="success">环境</td>
                <td class="info">路径</td>
                <td class="success">服务器</td>
                <td class="info">发布任务</td>
                <td class="info">操作</td>
            </tr>
            </thead>
            <tbody>
            <tbody>
            {% for project_env in project_envs %}
                {{ project_env.deploytask_set.count }}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ project_env.project }}</td>
                    <td>{{ project_env.get_env_display }}</td>
                    <td>{{ project_env.path }}</td>
                    <td>{% for server in project_env.servers.all %}{{ server }}{% endfor %}</td>
                    <td><a href="{% url 'web:deploy_task' project_env.id %}">发布({% un_deploy_num project_env %})</a>
                    </td>
                    <td>
                        <a style="color: #333333;" href="{% url 'web:project_env_edit' project_env.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="{% url 'web:project_env_delete' project_env.id %}"><i
                                class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
            </tbody>
        </table>

    </div>

{% endblock content %}
</body>
</html>

templates/web/project_env_add_edit.html
{% extends 'web/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ project_env_form }}
        <input type="submit" class="btn btn-success" value="提交">
    </form>
{% endblock content %}

templates/web/rsa.html
{% extends 'web/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RSA</title>
</head>
<body>
{% block content %}
    <div class="col-md-12" style="min-height: 500px;">
        <p class="">
            <a href="{% url 'web:rsa_add' %}">
                <button type="button" class="btn btn-primary">添加密钥</button>
            </a>
        </p>
        <p>
        <h3 class="text-center">密钥列表</h3>
        </p>
        <table class="table table-bordered table-striped table-hover">
            <!-- On rows -->
            <thead>
            <tr>
                <td class="success">编号</td>
                <td class="info">状态</td>
                <td class="success">密钥</td>
                <td class="info">操作</td>
            </tr>
            </thead>
            <tbody>
            <tbody>
            {% for rsa in rsas %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ rsa.get_status_display }}</td>
                    <td class="col-md-8">{{ rsa.private_key|truncatechars:20 }}</td>

                    <td>
                        <a style="color: #333333;" href="{% url 'web:rsa_edit' rsa.id %}">
                            <i class="fa fa-edit" aria-hidden="true"></i></a>
                        |
                        <a style="color: #d9534f;" href="{% url 'web:rsa_delete' rsa.id %}"><i
                                class="fa fa-trash-o"></i></a>

                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    <div class="col-md-offset-4">{{ page_html }}</div>
{% endblock content %}
</body>
</html>

templates/web/rsa_add_edit.html
{% extends 'web/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ rsa_form }}
        <input type="submit" class="btn btn-success" value="提交">
    </form>
{% endblock content %}

templates/web/server_add_edit.html
{% extends 'web/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ server_form }}
        <input type="submit" class="btn btn-success" value="提交">
    </form>
{% endblock content %}

templates/web/server_edit.html
{% extends 'web/base.html' %}
{% block content %}
    <p>编辑服务器</p>
    <form method="post">
        {% csrf_token %}
        <label for="hostname">服务器</label>
        {{ server_form }}
        <input type="submit" value="提交">
    </form>

{% endblock content %}